FROM node:lts-alpine

LABEL decription="Development image for StockStalker frontend."

WORKDIR /app

COPY package*.json ./

RUN npm install -g @ionic/cli native-run cordova-res --unsafe-perm

RUN npm ci

COPY . .

CMD ["npm", "run", "dev"]
