FROM node:lts-buster-slim

LABEL decription="Development image for StockStalker frontend."

WORKDIR /usr/src/app

HEALTHCHECK --interval=1m --timeout=5s --retries=2 \
  CMD curl -f http://localhost || exit 1

RUN rm /usr/bin/chage && rm /sbin/unix_chkpwd && rm /usr/bin/chsh && rm /usr/bin/gpasswd && \
  rm /bin/su && rm /usr/bin/expiry && rm /usr/bin/newgrp && rm /bin/mount && rm /usr/bin/chfn && \
  rm /bin/umount && rm /usr/bin/passwd && rm /usr/bin/wall

COPY package.json .

# RUN groupadd -g 999 nonroot && useradd -r -u 999 -g nonroot nonroot
# 
# USER nonroot
# 
# RUN mkdir -p ~/.npm-global
# 
# RUN NPM_CONFIG_PREFIX=~/.npm-global >> ~/.bashrc
# 
# RUN bash

RUN npm install -g @ionic/cli native-run cordova-res --unsafe-perm

RUN npm install

# RUN rm -r /root/.npm && rm /usr/src/app/node_modules/@surma/rollup-plugin-off-main-thread/Dockerfile

COPY . .

EXPOSE 8100

CMD ["npm", "run", "dev"]
