version: "3.9"
services:
  frontend:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: frontend
    volumes:
      - ./public:/usr/src/app/public
      - ./src:/usr/src/app/src
      - ./capacitor.config.json:/usr/src/app/capacitor.config.json
      - ./ionic.config.json:/usr/src/app/ionic.config.json
      - ./package.json:/usr/src/app/package.json
      - ./tsconfig.json:/usr/src/app/tsconfig.json
    env_file:
      - .env
    ports:
      - 8080:8100
    networks:
      - stockstalker-network

networks:
  stockstalker-network:
    driver: bridge
