FROM node:14.19.1-buster-slim

LABEL decription="Development image for StockStalker frontend."

WORKDIR /usr/src/app

HEALTHCHECK --interval=1m --timeout=5s --retries=2 \
  CMD curl -f http://localhost || exit 1

COPY package*.json ./

RUN npm ci

COPY . .

EXPOSE 8100

CMD ["npm", "run", "dev"]