version: "3.9"
services:
  frontend:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: frontend
    volumes:
      - .:/app
    env_file:
      - .env
    ports:
      - 8080:8100
    networks:
      - stockstalker-network

networks:
  stockstalker-network:
    driver: bridge
