version: "3.9"
services:
  frontend:
    restart: always
    container_name: frontend
    image: index.docker.io/starlightromero/stockstalker-frontend
    env_file:
      - .env
    networks:
      - stockstalker-network

networks:
  stockstalker-network:
    driver: bridge
